version: "3.7"
services:
  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    depends_on:
    - mongo_seed
  mongo_seed:
    image: "mongo:4.4.3"
    volumes:
      - ./db_files:/db_files
    command:
      /db_files/import.sh
  service:
    image: 'maven:latest'
    build:
      context: ./data-service/
    container_name: app
    depends_on:
      - mongo_db
    ports:
    - 5000:5000